stepper_motor_controller:
  type: "position_controllers/JointPositionController"
  joint: base_link1_part1_joint
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
servo_motor_1_controller:
  type: "position_controllers/JointPositionController"
  joint: link1_part2_link2_part1_joint
  pid:
    p: 1.0
    i: 0.0
    d: 0.0
servo_motor_2_controller:
  type: "position_controllers/JointPositionController"
  joint: link2_part3_link3_part1_joint
  pid:
    p: 1.0
    i: 0.0
    d: 0.0    
servo_motor_3_controller:
  type: "position_controllers/JointPositionController"
  joint: link3_part2_link4_part1_joint
  pid:
    p: 1.0
    i: 0.0
    d: 0.0    